# Generated by Django 5.1.6 on 2025-02-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_beat_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='beat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
