# Generated by Django 5.1.6 on 2025-02-16 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_uploaded_at_beat_created_at_beat_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='audio_file',
            field=models.FileField(upload_to='beats/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='beat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='beat',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
