# Generated by Django 5.1.6 on 2025-02-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='beat_covers/'),
        ),
    ]
