# Generated by Django 5.1.6 on 2025-02-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_beat_cover_image'),
        ('store', 'create_profiles'),
    ]

    operations = [
    ]
