# Generated by Django 5.1.6 on 2025-02-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_merge_0008_beat_cover_image_create_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beat',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
    ]
